sonar.organization=nleperson
sonar.projectKey=nleperson_courssecu_front
sonar.projectVersion=1.0.0
sonar.projectEncoding=UTF-8

sonar.language=js
sonar.sources=src
sonar.tests=cypress/e2e
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/*,cypress/*
sonar.qualityGate.wait=false