sonar.organization=nleperson
sonar.projectKey=nleperson_courssecu_back
sonar.projectVersion=1.0.0
sonar.projectEncoding=UTF-8

sonar.language=js
sonar.sources=api
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/*,test/*
sonar.qualityGate.wait=false