name: 02-3 - Deploy

on: workflow_call

jobs:
  AzureServer:
    runs-on: ubuntu-22.04

    env:
      ResourceGroupName: "Toutpetech"
      ResourceGroupLocation: "francecentral"

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI Resource Group
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}

      - name: Azure Bicep Deply
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ env.ResourceGroupName }}
          scope: resourcegroup
          template: ./main.bicep
          parameters: >
            adminUserName=${{ secrets.AZURE_VM_LOGIN }}
            adminPasswordOrKey=${{ secrets.AZURE_VM_PASSWORD }}
            vmName=vm-stagging
            vmSize=Standard_B2s

      - name: Open Port on Security Group
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az network nsg rule create --resource-group ${{env.ResourceGroupName}} --nsg-name SecGroupNet --name PortBack-12000 --priority 100 --direction Inbound --access Allow --protocol Tcp --source-address-prefixes "*" --source-port-ranges "*" --destination-address-prefixes "*" --destination-port-ranges 12000
            az network nsg rule create --resource-group ${{env.ResourceGroupName}} --nsg-name SecGroupNet --name PortFront-80 --priority 101 --direction Inbound --access Allow --protocol Tcp --source-address-prefixes "*" --source-port-ranges "*" --destination-address-prefixes "*" --destination-port-ranges 80

      - name: Get Public IP et créer règle
        if: success()
        uses: azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az vm show -d -g ${{env.ResourceGroupName}} -n vm-stagging --query publicIps -o tsv
            echo "AZURE_VM_IP=$(az vm show -d -g ${{env.ResourceGroupName}} -n vm-stagging --query publicIps -o tsv)" >> $GITHUB_ENV

      - name: Install Docker on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.AZURE_VM_IP}}
          port: ${{secrets.PORT}}
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}
          script: |
            curl -o install_docker.sh https://raw.githubusercontent.com/Base-Auto/scripts/refs/heads/main/install_docker_quick.sh
            ls -al
            bash ./install_docker.sh
