name: 01 - Integration

on:
  push:
    branches:
      - main

jobs:
  Test_Back_Front:
    uses: ./.github/workflows/01-1_TestBackFront.yml

  Quality_Sonarqube:
    needs: [Test_Back_Front]
    uses: ./.github/workflows/01-2_SonarQube.yml
    secrets: inherit

  # Security_Snyk:
